apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multicluster-observability-anonymous-grafana
    observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
  name: anonymous-grafana
  namespace: open-cluster-management-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-observability-anonymous-grafana
      observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
  template:
    metadata:
      labels:
        app: multicluster-observability-anonymous-grafana
        observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multicluster-observability-anonymous-grafana
          - weight: 30
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multicluster-observability-anonymous-grafana
      containers:
      - args:
        - -config=/etc/grafana/grafana.ini
        image: quay.io/open-cluster-management/grafana:2.4.0-SNAPSHOT-2021-09-23-07-02-14
        imagePullPolicy: IfNotPresent
        name: anonymous-grafana
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 4m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
        - mountPath: /etc/grafana
          name: grafana-config
      - args:
        - -from=AnonymousGrafana
        name: grafana-dashboard-loader
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/open-cluster-management/grafana-dashboard-loader:2.3.0-SNAPSHOT-2021-07-26-18-43-26
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 4m
            memory: 50Mi  
      serviceAccount: anonymous-grafana
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      serviceAccountName: anonymous-grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-datasources
        secret:
          defaultMode: 420
          secretName: anonymous-grafana-datasources
      - name: grafana-config
        secret:
          defaultMode: 420
          secretName: anonymous-grafana-config
