/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	time "time"

	versioned "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/client/clientset/versioned"
	internalinterfaces "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/client/informers/externalversions/internalinterfaces"
	v1beta2 "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/client/listers/multiclusterobservability/v1beta2"
	multiclusterobservabilityv1beta2 "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MultiClusterObservabilityInformer provides access to a shared informer and lister for
// MultiClusterObservabilities.
type MultiClusterObservabilityInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta2.MultiClusterObservabilityLister
}

type multiClusterObservabilityInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMultiClusterObservabilityInformer constructs a new informer for MultiClusterObservability type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMultiClusterObservabilityInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMultiClusterObservabilityInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMultiClusterObservabilityInformer constructs a new informer for MultiClusterObservability type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMultiClusterObservabilityInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ObservabilityV1beta2().MultiClusterObservabilities().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ObservabilityV1beta2().MultiClusterObservabilities().Watch(context.TODO(), options)
			},
		},
		&multiclusterobservabilityv1beta2.MultiClusterObservability{},
		resyncPeriod,
		indexers,
	)
}

func (f *multiClusterObservabilityInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMultiClusterObservabilityInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *multiClusterObservabilityInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&multiclusterobservabilityv1beta2.MultiClusterObservability{}, f.defaultInformer)
}

func (f *multiClusterObservabilityInformer) Lister() v1beta2.MultiClusterObservabilityLister {
	return v1beta2.NewMultiClusterObservabilityLister(f.Informer().GetIndexer())
}
