apiVersion: v1
data:
  thanos.yaml: dHlwZTogczMKY29uZmlnOgogIGJ1Y2tldDogInRoYW5vcyIKICBlbmRwb2ludDogIm1pbmlvOjkwMDAiCiAgaW5zZWN1cmU6IGZhbHNlCiAgYWNjZXNzX2tleTogIm1pbmlvIgogIHNlY3JldF9rZXk6ICJtaW5pbzEyMyIKICB0bHNfY29uZmlnOgogICAgY2FfZmlsZTogL2V0Yy9taW5pby9jZXJ0cy9jYS5jcnQKICAgIGNlcnRfZmlsZTogL2V0Yy9taW5pby9jZXJ0cy9wdWJsaWMuY3J0CiAgICBrZXlfZmlsZTogL2V0Yy9taW5pby9jZXJ0cy9wcml2YXRlLmtleQogICAgaW5zZWN1cmVfc2tpcF92ZXJpZnk6IGZhbHNlCg==
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
