apiVersion: v1
data:
  thanos.yaml: dHlwZTogczMNCmNvbmZpZzoNCiAgYnVja2V0OiAidGhhbm9zIg0KICBlbmRwb2ludDogIm1pbmlvOjkwMDAiDQogIGluc2VjdXJlOiBmYWxzZQ0KICBhY2Nlc3Nfa2V5OiAibWluaW8iDQogIHNlY3JldF9rZXk6ICJtaW5pbzEyMyINCiAgaHR0cF9jb25maWc6DQogICAgdGxzX2NvbmZpZzoNCiAgICAgIGNhX2ZpbGU6IC9ldGMvbWluaW8vY2VydHMvY2EuY3J0DQogICAgICBjZXJ0X2ZpbGU6IC9ldGMvbWluaW8vY2VydHMvcHVibGljLmNydA0KICAgICAga2V5X2ZpbGU6IC9ldGMvbWluaW8vY2VydHMvcHJpdmF0ZS5rZXkNCiAgICAgIGluc2VjdXJlX3NraXBfdmVyaWZ5OiBmYWxzZQ==
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
