/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	scheme "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/client/clientset/versioned/scheme"
	v1beta2 "github.com/open-cluster-management/multicluster-observability-operator/operators/pkg/apis/multiclusterobservability/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterObservabilitiesGetter has a method to return a MultiClusterObservabilityInterface.
// A group's client should implement this interface.
type MultiClusterObservabilitiesGetter interface {
	MultiClusterObservabilities() MultiClusterObservabilityInterface
}

// MultiClusterObservabilityInterface has methods to work with MultiClusterObservability resources.
type MultiClusterObservabilityInterface interface {
	Create(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.CreateOptions) (*v1beta2.MultiClusterObservability, error)
	Update(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.UpdateOptions) (*v1beta2.MultiClusterObservability, error)
	UpdateStatus(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.UpdateOptions) (*v1beta2.MultiClusterObservability, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.MultiClusterObservability, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.MultiClusterObservabilityList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.MultiClusterObservability, err error)
	MultiClusterObservabilityExpansion
}

// multiClusterObservabilities implements MultiClusterObservabilityInterface
type multiClusterObservabilities struct {
	client rest.Interface
}

// newMultiClusterObservabilities returns a MultiClusterObservabilities
func newMultiClusterObservabilities(c *ObservabilityV1beta2Client) *multiClusterObservabilities {
	return &multiClusterObservabilities{
		client: c.RESTClient(),
	}
}

// Get takes name of the multiClusterObservability, and returns the corresponding multiClusterObservability object, and an error if there is any.
func (c *multiClusterObservabilities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.MultiClusterObservability, err error) {
	result = &v1beta2.MultiClusterObservability{}
	err = c.client.Get().
		Resource("multiclusterobservabilities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterObservabilities that match those selectors.
func (c *multiClusterObservabilities) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.MultiClusterObservabilityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.MultiClusterObservabilityList{}
	err = c.client.Get().
		Resource("multiclusterobservabilities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterObservabilities.
func (c *multiClusterObservabilities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("multiclusterobservabilities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiClusterObservability and creates it.  Returns the server's representation of the multiClusterObservability, and an error, if there is any.
func (c *multiClusterObservabilities) Create(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.CreateOptions) (result *v1beta2.MultiClusterObservability, err error) {
	result = &v1beta2.MultiClusterObservability{}
	err = c.client.Post().
		Resource("multiclusterobservabilities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterObservability).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiClusterObservability and updates it. Returns the server's representation of the multiClusterObservability, and an error, if there is any.
func (c *multiClusterObservabilities) Update(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.UpdateOptions) (result *v1beta2.MultiClusterObservability, err error) {
	result = &v1beta2.MultiClusterObservability{}
	err = c.client.Put().
		Resource("multiclusterobservabilities").
		Name(multiClusterObservability.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterObservability).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *multiClusterObservabilities) UpdateStatus(ctx context.Context, multiClusterObservability *v1beta2.MultiClusterObservability, opts v1.UpdateOptions) (result *v1beta2.MultiClusterObservability, err error) {
	result = &v1beta2.MultiClusterObservability{}
	err = c.client.Put().
		Resource("multiclusterobservabilities").
		Name(multiClusterObservability.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterObservability).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiClusterObservability and deletes it. Returns an error if one occurs.
func (c *multiClusterObservabilities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("multiclusterobservabilities").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterObservabilities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("multiclusterobservabilities").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiClusterObservability.
func (c *multiClusterObservabilities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.MultiClusterObservability, err error) {
	result = &v1beta2.MultiClusterObservability{}
	err = c.client.Patch(pt).
		Resource("multiclusterobservabilities").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
