apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-agent-operator
  namespace: open-cluster-management-observability
  labels:
    name: observability-agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: observability-agent-operator
  template:
    metadata:
      labels:
        name: observability-agent-operator
    spec:
      serviceAccountName: observability-agent-operator
      containers:
      - name: observability-agent-operator
        command:
        - observability-agent
        args:
        - -leader-elect
        # Replace this with the built image name
        image: quay.io/open-cluster-management/observability-agent-operator:2.3.0-SNAPSHOT-2021-07-26-18-43-26
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8383
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 600m
            memory: 1024Mi
          requests:
            cpu: 20m
            memory: 128Mi
        env:
          - name: WATCH_NAMESPACE
            value: ""
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MCO_POD_NAMESPACE
            value: open-cluster-management
          - name: TEMPLATES_PATH
            value: /usr/local/manifests
          - name: SPOKE_NAMESPACE
            value: open-cluster-management-addon-observability
          - name: OBSERVABILITY_CORE_KUBECONFIG
            value: "/observability/core-kubeconfig/kubeconfig"
        volumeMounts:
          - name: observability-core-kubeconfig-secret
            mountPath: "/observability/core-kubeconfig"
            readOnly: true
      volumes:
        - name: observability-core-kubeconfig-secret
          secret:
            secretName: observability-core-kubeconfig
